$axure.loadCurrentPage({
  "url":"dados_requerente_interno.html",
  "generationDate":new Date(1399038421314.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ef3b6f852dc848819aad62afcb278ba3",
    "type":"Axure:Page",
    "name":"Dados Requerente Interno",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"abcb27e50c544c4581fbbd968b8aa2eb",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"c3b312e0f4ed4c0bb3018e5ca722b50c"},
{
          "id":"ba02d6b99748494386a253224a41e861",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":180,
              "y":188},
            "size":{
              "width":180,
              "height":22},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"solid"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be04e926622944de8c88afc963dc7358",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":180,
                  "y":188},
                "size":{
                  "width":180,
                  "height":22},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "linePattern":"solid"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cadastromanifesta_ao/u15_mouseOver.png"}},
{
          "id":"ec3b73136a304b0a8475c51cd3085f37",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":360,
              "y":188},
            "size":{
              "width":200,
              "height":22},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"solid"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2281d193b614f64a351695c0eea9eb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":360,
                  "y":188},
                "size":{
                  "width":200,
                  "height":22},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "linePattern":"solid"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cadastromanifesta_ao/u17.png"}},
{
          "id":"adbbb9f8fb264645b9fb990b7c2ea0aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":560,
              "y":188},
            "size":{
              "width":200,
              "height":22},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"solid"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cf07e2208a44f88b44e1e5a33b38dbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":560,
                  "y":188},
                "size":{
                  "width":200,
                  "height":22},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "linePattern":"solid"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cadastromanifesta_ao/u17.png"}},
{
          "id":"5afbc6e1c616464789c430caec0b8f64",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrito', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":24,
              "y":161},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a12586b620b415285026c8ed4cf89d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negrito', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":24,
                  "y":161},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e234fbf3ee54cd8b9cb0c1b6c815d70",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":180,
              "y":210},
            "size":{
              "width":580,
              "height":127},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13aa90add68c4942a7c448aafaf90d7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":180,
                  "y":210},
                "size":{
                  "width":580,
                  "height":127},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cadastromanifesta_ao/u24.png"}},
{
          "id":"5155c74a49d643c7b12f6b5f982d1720",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrito', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":198,
              "y":225},
            "size":{
              "width":78,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12054e3fc906458eb4bc54556799359f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negrito', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":198,
                  "y":225},
                "size":{
                  "width":78,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6f383ca7e904627a566e6982a4fb812",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":201,
              "y":259},
            "size":{
              "width":46,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab1684896c3e4ee0ab68db993dc6b9c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":201,
                  "y":259},
                "size":{
                  "width":46,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"630e3ed58de347478915c1d38b471764",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":239},
            "size":{
              "width":560,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/cadastromanifesta_ao/u30_line.png"}},
{
          "id":"67b1a860d00c4147a4aa97c810ec8b46",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":201,
              "y":308},
            "size":{
              "width":28,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17122bdc326a4916a471610a48f4396f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":201,
                  "y":308},
                "size":{
                  "width":28,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37d6a124487547429d5fcae35f052bc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":201,
              "y":282},
            "size":{
              "width":48,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e497bc8d4390432ca7f81927aa7e84fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":201,
                  "y":282},
                "size":{
                  "width":48,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"791f6601966849629103414ede9dcf88",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":279},
            "size":{
              "width":340,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"06726a327bb741189951d25e9d81dfb7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":249},
            "size":{
              "width":340,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"36e73fd084a34a779309506d7fbf5316",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":410,
              "y":308},
            "size":{
              "width":200,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"dd379a2960754892b74be83687d6c994",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":180,
              "y":337},
            "size":{
              "width":580,
              "height":343},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"154ec1b6278f4c2da2af8cb0729c6a50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":180,
                  "y":337},
                "size":{
                  "width":580,
                  "height":343},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cadastromanifesta_ao/u38.png"}},
{
          "id":"0731797e38b0400b86e1b93f160affa9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrito', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":196,
              "y":341},
            "size":{
              "width":215,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e8e343ceab34974bf25c11e58e90374",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negrito', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":196,
                  "y":341},
                "size":{
                  "width":215,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2efeae3493f4aee8fd7153435550259",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":200,
              "y":366},
            "size":{
              "width":255,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bb316b1f50b4c8c9b26ba05124b2b8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":200,
                  "y":366},
                "size":{
                  "width":255,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a64d0d8925a1492b9cf3a2bc81ad4ab9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":356},
            "size":{
              "width":560,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/cadastromanifesta_ao/u30_line.png"}},
{
          "id":"d5b0e75ac7364a54b4c6535f024043d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":201,
              "y":389},
            "size":{
              "width":152,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99eb725df84e4d548cddfc0ac60e4e92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":201,
                  "y":389},
                "size":{
                  "width":152,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b192950b4584ecfb7994149a5a06eda",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":201,
              "y":414},
            "size":{
              "width":28,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97223c6f646042a6bb7ea9349f32299d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":201,
                  "y":414},
                "size":{
                  "width":28,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd8b61f6ce2e4463b4c069e116491efa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":201,
              "y":464},
            "size":{
              "width":65,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ffd1a1ed5654f5593bb9fec944a7876",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":201,
                  "y":464},
                "size":{
                  "width":65,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb58527e23f44bccbefc0d1387b8e8c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":201,
              "y":489},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4f2cadd8ccb4901b27fae23be56afa3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":201,
                  "y":489},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ae8e3b612974b6d9971480d7838365f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":201,
              "y":587},
            "size":{
              "width":113,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92e90b9059384acc8c42c4961b93d1f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":201,
                  "y":587},
                "size":{
                  "width":113,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eaeae658dba841258da87717b9c6ef69",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":201,
              "y":537},
            "size":{
              "width":176,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a19527d444d4edfae051aca88afa68f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":201,
                  "y":537},
                "size":{
                  "width":176,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d074de2a27448d1bcc8e9b518b6fc07",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":201,
              "y":514},
            "size":{
              "width":51,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73e94a366490423d8bbaf3e51c1367a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":201,
                  "y":514},
                "size":{
                  "width":51,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5c8291dd1684625ae98fbbe4e6352c4",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":410,
              "y":384},
            "size":{
              "width":200,
              "height":21}},
          "adaptiveStyles":{
}},
{
          "id":"23f576cc62194d00aa1242cabafda49a",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":410,
              "y":533},
            "size":{
              "width":200,
              "height":21}},
          "adaptiveStyles":{
}},
{
          "id":"9b008d01b7534ff8a1c6fa8e5b8c76a8",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":410,
              "y":588},
            "size":{
              "width":200,
              "height":21}},
          "adaptiveStyles":{
}},
{
          "id":"9fe92864ff6a4514a11e635693b81da1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":410,
              "y":412},
            "size":{
              "width":200,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"938b69520cec4309bffe15384d3ddb4e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":410,
              "y":443},
            "size":{
              "width":200,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"d9e69af247b14bb89fe68e3e06adcfba",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":410,
              "y":472},
            "size":{
              "width":200,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"8d6695c871c447deb67d98ff46bc483c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":410,
              "y":503},
            "size":{
              "width":200,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"8731789857784c67930a03970d9b4cb3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":410,
              "y":611},
            "size":{
              "width":200,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"ddb7122a6ee641bd86cd1a42024fc460",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":620,
              "y":610},
            "size":{
              "width":130,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"463893bdfbef4b368d45558409f6a569",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":200,
              "y":643},
            "size":{
              "width":100,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"91c02397d2f5403fa0911c99a8ab1010",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":620,
              "y":643},
            "size":{
              "width":130,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"19a6b9b6d0a94019b87224a36ebd619d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":635},
            "size":{
              "width":560,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/cadastromanifesta_ao/u70_line.png"}},
{
          "id":"aefd9fff5dfc4366b9f71c9fec5b5af6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":201,
              "y":439},
            "size":{
              "width":64,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad261b235af3458cbb52c34cd985d235",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":201,
                  "y":439},
                "size":{
                  "width":64,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca94700d55dc48d0b6b341f1992b1b55",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":201,
              "y":562},
            "size":{
              "width":186,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5d906e1828644cd81fce51e8a080246",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":201,
                  "y":562},
                "size":{
                  "width":186,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc01bd9b16ea45228b71b1cac6bd3cee",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":410,
              "y":561},
            "size":{
              "width":200,
              "height":21}},
          "adaptiveStyles":{
}},
{
          "id":"b8af3a088a9a430eb300a26aea4be7b1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":320,
              "y":643},
            "size":{
              "width":130,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"5f2ab41395d641fdab1df25d63af1385",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":470,
              "y":643},
            "size":{
              "width":130,
              "height":24}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "c3b312e0f4ed4c0bb3018e5ca722b50c":{
      "packageId":"c3b312e0f4ed4c0bb3018e5ca722b50c",
      "type":"Axure:Master",
      "name":"MasterOuvidoria",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"85041cc9a6574e6995adfae7d06a0ed6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":776,
                "height":768}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13c32486200e4ff188916d5c4c5dd53d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":776,
                    "height":768}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u1.jpg"}},
{
            "id":"6af9268f4a684618a3d22d2e33f87b18",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":540,
                "y":570},
              "size":{
                "width":200,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5a03389ad0f94aceb449f367debbd1d0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":540,
                    "y":570},
                  "size":{
                    "width":200,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u3.png"}},
{
            "id":"b105428545ea4d8caaf90e64e90e98ce",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":540,
                "y":190},
              "size":{
                "width":200,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"058af3d369864a16b0e46da395b65894",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":540,
                    "y":190},
                  "size":{
                    "width":200,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u3.png"}},
{
            "id":"acb38523bb214e7497cbd28b2ca26e91",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Rounded MT Bold', 'Arial Rounded MT'",
              "fontSize":"12px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0033CC,
                "opacity":1},
              "location":{
                "x":190,
                "y":164},
              "size":{
                "width":126,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aee5318bf07847c99662fb659f4942be",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Rounded MT Bold', 'Arial Rounded MT'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0033CC,
                    "opacity":1},
                  "location":{
                    "x":190,
                    "y":164},
                  "size":{
                    "width":126,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"660cfdf55c5b442f9574a2984b321745",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":180,
                "y":200},
              "size":{
                "width":200,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"99eb6015e68a4e9abf3a0e51107c7e86",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":180,
                    "y":200},
                  "size":{
                    "width":200,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u9.png"}},
{
            "id":"6dce9515c9164d5489b7b3e556cf9ed3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":180,
                "y":210},
              "size":{
                "width":200,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c1e04fb4630244a0bf26fdde812818d2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":180,
                    "y":210},
                  "size":{
                    "width":200,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u3.png"}},
{
            "id":"56003b8b0b10483085cb3bc23ef9b97d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negrito', 'Arial'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":24,
                "y":161},
              "size":{
                "width":70,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"78a482e4afeb4a3d9ffca2c3c2180110",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negrito', 'Arial'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":24,
                    "y":161},
                  "size":{
                    "width":70,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "abcb27e50c544c4581fbbd968b8aa2eb":{
      "scriptId":"u0",
      "85041cc9a6574e6995adfae7d06a0ed6":{
        "scriptId":"u1"},
      "13c32486200e4ff188916d5c4c5dd53d":{
        "scriptId":"u2"},
      "6af9268f4a684618a3d22d2e33f87b18":{
        "scriptId":"u3"},
      "5a03389ad0f94aceb449f367debbd1d0":{
        "scriptId":"u4"},
      "b105428545ea4d8caaf90e64e90e98ce":{
        "scriptId":"u5"},
      "058af3d369864a16b0e46da395b65894":{
        "scriptId":"u6"},
      "acb38523bb214e7497cbd28b2ca26e91":{
        "scriptId":"u7"},
      "aee5318bf07847c99662fb659f4942be":{
        "scriptId":"u8"},
      "660cfdf55c5b442f9574a2984b321745":{
        "scriptId":"u9"},
      "99eb6015e68a4e9abf3a0e51107c7e86":{
        "scriptId":"u10"},
      "6dce9515c9164d5489b7b3e556cf9ed3":{
        "scriptId":"u11"},
      "c1e04fb4630244a0bf26fdde812818d2":{
        "scriptId":"u12"},
      "56003b8b0b10483085cb3bc23ef9b97d":{
        "scriptId":"u13"},
      "78a482e4afeb4a3d9ffca2c3c2180110":{
        "scriptId":"u14"}},
    "ba02d6b99748494386a253224a41e861":{
      "scriptId":"u15"},
    "be04e926622944de8c88afc963dc7358":{
      "scriptId":"u16"},
    "ec3b73136a304b0a8475c51cd3085f37":{
      "scriptId":"u17"},
    "b2281d193b614f64a351695c0eea9eb6":{
      "scriptId":"u18"},
    "adbbb9f8fb264645b9fb990b7c2ea0aa":{
      "scriptId":"u19"},
    "3cf07e2208a44f88b44e1e5a33b38dbb":{
      "scriptId":"u20"},
    "5afbc6e1c616464789c430caec0b8f64":{
      "scriptId":"u21"},
    "0a12586b620b415285026c8ed4cf89d0":{
      "scriptId":"u22"},
    "0e234fbf3ee54cd8b9cb0c1b6c815d70":{
      "scriptId":"u23"},
    "13aa90add68c4942a7c448aafaf90d7e":{
      "scriptId":"u24"},
    "5155c74a49d643c7b12f6b5f982d1720":{
      "scriptId":"u25"},
    "12054e3fc906458eb4bc54556799359f":{
      "scriptId":"u26"},
    "f6f383ca7e904627a566e6982a4fb812":{
      "scriptId":"u27"},
    "ab1684896c3e4ee0ab68db993dc6b9c3":{
      "scriptId":"u28"},
    "630e3ed58de347478915c1d38b471764":{
      "scriptId":"u29"},
    "67b1a860d00c4147a4aa97c810ec8b46":{
      "scriptId":"u30"},
    "17122bdc326a4916a471610a48f4396f":{
      "scriptId":"u31"},
    "37d6a124487547429d5fcae35f052bc0":{
      "scriptId":"u32"},
    "e497bc8d4390432ca7f81927aa7e84fa":{
      "scriptId":"u33"},
    "791f6601966849629103414ede9dcf88":{
      "scriptId":"u34"},
    "06726a327bb741189951d25e9d81dfb7":{
      "scriptId":"u35"},
    "36e73fd084a34a779309506d7fbf5316":{
      "scriptId":"u36"},
    "dd379a2960754892b74be83687d6c994":{
      "scriptId":"u37"},
    "154ec1b6278f4c2da2af8cb0729c6a50":{
      "scriptId":"u38"},
    "0731797e38b0400b86e1b93f160affa9":{
      "scriptId":"u39"},
    "6e8e343ceab34974bf25c11e58e90374":{
      "scriptId":"u40"},
    "b2efeae3493f4aee8fd7153435550259":{
      "scriptId":"u41"},
    "4bb316b1f50b4c8c9b26ba05124b2b8f":{
      "scriptId":"u42"},
    "a64d0d8925a1492b9cf3a2bc81ad4ab9":{
      "scriptId":"u43"},
    "d5b0e75ac7364a54b4c6535f024043d4":{
      "scriptId":"u44"},
    "99eb725df84e4d548cddfc0ac60e4e92":{
      "scriptId":"u45"},
    "6b192950b4584ecfb7994149a5a06eda":{
      "scriptId":"u46"},
    "97223c6f646042a6bb7ea9349f32299d":{
      "scriptId":"u47"},
    "bd8b61f6ce2e4463b4c069e116491efa":{
      "scriptId":"u48"},
    "5ffd1a1ed5654f5593bb9fec944a7876":{
      "scriptId":"u49"},
    "cb58527e23f44bccbefc0d1387b8e8c1":{
      "scriptId":"u50"},
    "e4f2cadd8ccb4901b27fae23be56afa3":{
      "scriptId":"u51"},
    "2ae8e3b612974b6d9971480d7838365f":{
      "scriptId":"u52"},
    "92e90b9059384acc8c42c4961b93d1f9":{
      "scriptId":"u53"},
    "eaeae658dba841258da87717b9c6ef69":{
      "scriptId":"u54"},
    "0a19527d444d4edfae051aca88afa68f":{
      "scriptId":"u55"},
    "5d074de2a27448d1bcc8e9b518b6fc07":{
      "scriptId":"u56"},
    "73e94a366490423d8bbaf3e51c1367a7":{
      "scriptId":"u57"},
    "a5c8291dd1684625ae98fbbe4e6352c4":{
      "scriptId":"u58"},
    "23f576cc62194d00aa1242cabafda49a":{
      "scriptId":"u59"},
    "9b008d01b7534ff8a1c6fa8e5b8c76a8":{
      "scriptId":"u60"},
    "9fe92864ff6a4514a11e635693b81da1":{
      "scriptId":"u61"},
    "938b69520cec4309bffe15384d3ddb4e":{
      "scriptId":"u62"},
    "d9e69af247b14bb89fe68e3e06adcfba":{
      "scriptId":"u63"},
    "8d6695c871c447deb67d98ff46bc483c":{
      "scriptId":"u64"},
    "8731789857784c67930a03970d9b4cb3":{
      "scriptId":"u65"},
    "ddb7122a6ee641bd86cd1a42024fc460":{
      "scriptId":"u66"},
    "463893bdfbef4b368d45558409f6a569":{
      "scriptId":"u67"},
    "91c02397d2f5403fa0911c99a8ab1010":{
      "scriptId":"u68"},
    "19a6b9b6d0a94019b87224a36ebd619d":{
      "scriptId":"u69"},
    "aefd9fff5dfc4366b9f71c9fec5b5af6":{
      "scriptId":"u70"},
    "ad261b235af3458cbb52c34cd985d235":{
      "scriptId":"u71"},
    "ca94700d55dc48d0b6b341f1992b1b55":{
      "scriptId":"u72"},
    "b5d906e1828644cd81fce51e8a080246":{
      "scriptId":"u73"},
    "fc01bd9b16ea45228b71b1cac6bd3cee":{
      "scriptId":"u74"},
    "b8af3a088a9a430eb300a26aea4be7b1":{
      "scriptId":"u75"},
    "5f2ab41395d641fdab1df25d63af1385":{
      "scriptId":"u76"}}});