$axure.loadCurrentPage({
  "url":"pedido_de_acesso_a_informa_ao.html",
  "generationDate":new Date(1399038420741.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b4d5d56460c54bfb97e39711b6b9be62",
    "type":"Axure:Page",
    "name":"Pedido de Acesso à Informação",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bdadd747ea4d4bd1b571cf001255ada9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"3b16d9b8a6d3471c8e3cd296e0e9b3da"},
{
          "id":"dfa2e3b8b5ed46bdaccb8ccebc150650",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "size":{
              "width":776,
              "height":123},
            "borderFill":{
              "fillType":"solid",
              "color":0x282828}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e6f1ec9a62c4d51a5dfb1c5db7a5d0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "size":{
                  "width":776,
                  "height":123},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x282828}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9732345cf9334e5e96922cfd54a529c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":580},
            "size":{
              "width":200,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69c2dbf4d4cf49258c4e06c577e06ad7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":580},
                "size":{
                  "width":200,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u3.png"}},
{
          "id":"259bc0f9e81b40a3a6c848006acde470",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":190},
            "size":{
              "width":90,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87da584a86ac476ab9b9f3742d5e03d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":190},
                "size":{
                  "width":90,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u17.png"}},
{
          "id":"91a11bda07134a5f9a9ce07ac07408e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0066CC},
            "location":{
              "x":392.5,
              "y":300},
            "size":{
              "width":155,
              "height":50},
            "cornerRadiusTopLeft":"5",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":102,
                "g":102,
                "b":102,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"294590b68bc843368bd7c2a5a960b013",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066CC},
                "location":{
                  "x":392.5,
                  "y":300},
                "size":{
                  "width":155,
                  "height":50},
                "cornerRadiusTopLeft":"5",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":102,
                    "g":102,
                    "b":102,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pedido_de_acesso_a_informa_ao/u21.png"}},
{
          "id":"2d16780acb214eeb8feca54b819d3214",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":216},
            "size":{
              "width":580,
              "height":244}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dea78415deef4d9ba6fbe7eb2b3782a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":216},
                "size":{
                  "width":580,
                  "height":244}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "3b16d9b8a6d3471c8e3cd296e0e9b3da":{
      "packageId":"3b16d9b8a6d3471c8e3cd296e0e9b3da",
      "type":"Axure:Master",
      "name":"MasterLAI",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"85041cc9a6574e6995adfae7d06a0ed6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":776,
                "height":768}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13c32486200e4ff188916d5c4c5dd53d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":776,
                    "height":768}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u1.jpg"}},
{
            "id":"6af9268f4a684618a3d22d2e33f87b18",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":540,
                "y":570},
              "size":{
                "width":200,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5a03389ad0f94aceb449f367debbd1d0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":540,
                    "y":570},
                  "size":{
                    "width":200,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u3.png"}},
{
            "id":"b105428545ea4d8caaf90e64e90e98ce",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":540,
                "y":190},
              "size":{
                "width":200,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"058af3d369864a16b0e46da395b65894",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":540,
                    "y":190},
                  "size":{
                    "width":200,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u3.png"}},
{
            "id":"acb38523bb214e7497cbd28b2ca26e91",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Rounded MT Bold', 'Arial Rounded MT'",
              "fontSize":"12px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0033CC,
                "opacity":1},
              "location":{
                "x":190,
                "y":164},
              "size":{
                "width":162,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aee5318bf07847c99662fb659f4942be",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Rounded MT Bold', 'Arial Rounded MT'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0033CC,
                    "opacity":1},
                  "location":{
                    "x":190,
                    "y":164},
                  "size":{
                    "width":162,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"660cfdf55c5b442f9574a2984b321745",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":180,
                "y":200},
              "size":{
                "width":200,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"99eb6015e68a4e9abf3a0e51107c7e86",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":180,
                    "y":200},
                  "size":{
                    "width":200,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u9.png"}},
{
            "id":"6dce9515c9164d5489b7b3e556cf9ed3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":180,
                "y":210},
              "size":{
                "width":200,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c1e04fb4630244a0bf26fdde812818d2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":180,
                    "y":210},
                  "size":{
                    "width":200,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u3.png"}},
{
            "id":"56003b8b0b10483085cb3bc23ef9b97d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negrito', 'Arial'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":24,
                "y":161},
              "size":{
                "width":98,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"78a482e4afeb4a3d9ffca2c3c2180110",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negrito', 'Arial'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":24,
                    "y":161},
                  "size":{
                    "width":98,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "bdadd747ea4d4bd1b571cf001255ada9":{
      "scriptId":"u0",
      "85041cc9a6574e6995adfae7d06a0ed6":{
        "scriptId":"u1"},
      "13c32486200e4ff188916d5c4c5dd53d":{
        "scriptId":"u2"},
      "6af9268f4a684618a3d22d2e33f87b18":{
        "scriptId":"u3"},
      "5a03389ad0f94aceb449f367debbd1d0":{
        "scriptId":"u4"},
      "b105428545ea4d8caaf90e64e90e98ce":{
        "scriptId":"u5"},
      "058af3d369864a16b0e46da395b65894":{
        "scriptId":"u6"},
      "acb38523bb214e7497cbd28b2ca26e91":{
        "scriptId":"u7"},
      "aee5318bf07847c99662fb659f4942be":{
        "scriptId":"u8"},
      "660cfdf55c5b442f9574a2984b321745":{
        "scriptId":"u9"},
      "99eb6015e68a4e9abf3a0e51107c7e86":{
        "scriptId":"u10"},
      "6dce9515c9164d5489b7b3e556cf9ed3":{
        "scriptId":"u11"},
      "c1e04fb4630244a0bf26fdde812818d2":{
        "scriptId":"u12"},
      "56003b8b0b10483085cb3bc23ef9b97d":{
        "scriptId":"u13"},
      "78a482e4afeb4a3d9ffca2c3c2180110":{
        "scriptId":"u14"}},
    "dfa2e3b8b5ed46bdaccb8ccebc150650":{
      "scriptId":"u15"},
    "9e6f1ec9a62c4d51a5dfb1c5db7a5d0e":{
      "scriptId":"u16"},
    "9732345cf9334e5e96922cfd54a529c5":{
      "scriptId":"u17"},
    "69c2dbf4d4cf49258c4e06c577e06ad7":{
      "scriptId":"u18"},
    "259bc0f9e81b40a3a6c848006acde470":{
      "scriptId":"u19"},
    "87da584a86ac476ab9b9f3742d5e03d2":{
      "scriptId":"u20"},
    "91a11bda07134a5f9a9ce07ac07408e7":{
      "scriptId":"u21"},
    "294590b68bc843368bd7c2a5a960b013":{
      "scriptId":"u22"},
    "2d16780acb214eeb8feca54b819d3214":{
      "scriptId":"u23"},
    "dea78415deef4d9ba6fbe7eb2b3782a5":{
      "scriptId":"u24"}}});