$axure.loadCurrentPage({
  "url":"esqueci_minha_senha.html",
  "generationDate":new Date(1399640624811.67),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"926a54da30b54378a8a054acac3b3aff",
    "type":"Axure:Page",
    "name":"Esqueci minha senha",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7ed82d1422c94f379737e7d2dfe28bff",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"c3b312e0f4ed4c0bb3018e5ca722b50c"},
{
          "id":"9732345cf9334e5e96922cfd54a529c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":580},
            "size":{
              "width":200,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69c2dbf4d4cf49258c4e06c577e06ad7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":580},
                "size":{
                  "width":200,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u3.png"}},
{
          "id":"e1c2b799e15249d7adff0ca37383dc9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":289},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be9e4b6bd35b4afb8afc70c4220ea579",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":289},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9682fbf9b3947af8810bd061d4482cd",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":305},
            "size":{
              "width":433,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4b45bb535dff41c98b8cf55afe417a6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":330},
            "size":{
              "width":350,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33cc0d19b9834a79a0c9709eb1298fb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":330},
                "size":{
                  "width":350,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b902b6eda5b94973badfdd9b45fe532a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":465},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d909ea53aa5142ef80018903296b2fda",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":190},
            "size":{
              "width":90,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abfb4e0ab65346e9803cbafb99ad572a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":190},
                "size":{
                  "width":90,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u17.png"}},
{
          "id":"412914260670490ca5e68f7cc320b295",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":199},
            "size":{
              "width":543,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2463e69158cc4374af2b50558b6457df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":185,
                  "y":199},
                "size":{
                  "width":543,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2cb3b847b7b44048bea915bb330bee61",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrito', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":24,
              "y":161},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db593896b7bd4bd5916712ec7ed2c421",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negrito', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":24,
                  "y":161},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "c3b312e0f4ed4c0bb3018e5ca722b50c":{
      "packageId":"c3b312e0f4ed4c0bb3018e5ca722b50c",
      "type":"Axure:Master",
      "name":"MasterOuvidoria",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"85041cc9a6574e6995adfae7d06a0ed6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":776,
                "height":768}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13c32486200e4ff188916d5c4c5dd53d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":776,
                    "height":768}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u1.jpg"}},
{
            "id":"6af9268f4a684618a3d22d2e33f87b18",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":540,
                "y":570},
              "size":{
                "width":200,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5a03389ad0f94aceb449f367debbd1d0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":540,
                    "y":570},
                  "size":{
                    "width":200,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u3.png"}},
{
            "id":"b105428545ea4d8caaf90e64e90e98ce",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":540,
                "y":190},
              "size":{
                "width":200,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"058af3d369864a16b0e46da395b65894",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":540,
                    "y":190},
                  "size":{
                    "width":200,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u3.png"}},
{
            "id":"acb38523bb214e7497cbd28b2ca26e91",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Rounded MT Bold', 'Arial Rounded MT'",
              "fontSize":"12px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0033CC,
                "opacity":1},
              "location":{
                "x":190,
                "y":164},
              "size":{
                "width":126,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aee5318bf07847c99662fb659f4942be",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Rounded MT Bold', 'Arial Rounded MT'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0033CC,
                    "opacity":1},
                  "location":{
                    "x":190,
                    "y":164},
                  "size":{
                    "width":126,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"660cfdf55c5b442f9574a2984b321745",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":180,
                "y":200},
              "size":{
                "width":200,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"99eb6015e68a4e9abf3a0e51107c7e86",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":180,
                    "y":200},
                  "size":{
                    "width":200,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u9.png"}},
{
            "id":"6dce9515c9164d5489b7b3e556cf9ed3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":180,
                "y":210},
              "size":{
                "width":200,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c1e04fb4630244a0bf26fdde812818d2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":180,
                    "y":210},
                  "size":{
                    "width":200,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u3.png"}},
{
            "id":"56003b8b0b10483085cb3bc23ef9b97d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negrito', 'Arial'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":24,
                "y":161},
              "size":{
                "width":70,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"78a482e4afeb4a3d9ffca2c3c2180110",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negrito', 'Arial'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":24,
                    "y":161},
                  "size":{
                    "width":70,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "7ed82d1422c94f379737e7d2dfe28bff":{
      "scriptId":"u0",
      "85041cc9a6574e6995adfae7d06a0ed6":{
        "scriptId":"u1"},
      "13c32486200e4ff188916d5c4c5dd53d":{
        "scriptId":"u2"},
      "6af9268f4a684618a3d22d2e33f87b18":{
        "scriptId":"u3"},
      "5a03389ad0f94aceb449f367debbd1d0":{
        "scriptId":"u4"},
      "b105428545ea4d8caaf90e64e90e98ce":{
        "scriptId":"u5"},
      "058af3d369864a16b0e46da395b65894":{
        "scriptId":"u6"},
      "acb38523bb214e7497cbd28b2ca26e91":{
        "scriptId":"u7"},
      "aee5318bf07847c99662fb659f4942be":{
        "scriptId":"u8"},
      "660cfdf55c5b442f9574a2984b321745":{
        "scriptId":"u9"},
      "99eb6015e68a4e9abf3a0e51107c7e86":{
        "scriptId":"u10"},
      "6dce9515c9164d5489b7b3e556cf9ed3":{
        "scriptId":"u11"},
      "c1e04fb4630244a0bf26fdde812818d2":{
        "scriptId":"u12"},
      "56003b8b0b10483085cb3bc23ef9b97d":{
        "scriptId":"u13"},
      "78a482e4afeb4a3d9ffca2c3c2180110":{
        "scriptId":"u14"}},
    "9732345cf9334e5e96922cfd54a529c5":{
      "scriptId":"u15"},
    "69c2dbf4d4cf49258c4e06c577e06ad7":{
      "scriptId":"u16"},
    "e1c2b799e15249d7adff0ca37383dc9e":{
      "scriptId":"u17"},
    "be9e4b6bd35b4afb8afc70c4220ea579":{
      "scriptId":"u18"},
    "a9682fbf9b3947af8810bd061d4482cd":{
      "scriptId":"u19"},
    "4b45bb535dff41c98b8cf55afe417a6c":{
      "scriptId":"u20"},
    "33cc0d19b9834a79a0c9709eb1298fb6":{
      "scriptId":"u21"},
    "b902b6eda5b94973badfdd9b45fe532a":{
      "scriptId":"u22"},
    "d909ea53aa5142ef80018903296b2fda":{
      "scriptId":"u23"},
    "abfb4e0ab65346e9803cbafb99ad572a":{
      "scriptId":"u24"},
    "412914260670490ca5e68f7cc320b295":{
      "scriptId":"u25"},
    "2463e69158cc4374af2b50558b6457df":{
      "scriptId":"u26"},
    "2cb3b847b7b44048bea915bb330bee61":{
      "scriptId":"u27"},
    "db593896b7bd4bd5916712ec7ed2c421":{
      "scriptId":"u28"}}});