$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1399640624568.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2b265bebd0234131b57bef924ada2f68",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1ce83de9629f429c8c3474f2e2e9de36",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"c3b312e0f4ed4c0bb3018e5ca722b50c"},
{
          "id":"d3bc5ec3745944889c4e0ba806c23a8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrito', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":24,
              "y":161},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a216607c7ced4c8ea7e177c36e6c631c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negrito', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":24,
                  "y":161},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5ddcaf17b53428ea6ee0ac3908f4ec9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":190},
            "size":{
              "width":90,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45490e93d1cb49c999b667aefced80be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":190},
                "size":{
                  "width":90,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u17.png"}},
{
          "id":"703a8af572e94ce69b489fa526ae3a43",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":210,
              "y":208},
            "size":{
              "width":470,
              "height":112}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae15c0c4e38c4e47bf18c8940ba62bcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":210,
                  "y":208},
                "size":{
                  "width":470,
                  "height":112}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23d4793a18774883aaf183ddeeb8ae76",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":263,
              "y":370.000030517578},
            "size":{
              "width":382,
              "height":281}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fcc53d3a6c04f9ab6faee5226508dab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":263,
                  "y":370.000030517578},
                "size":{
                  "width":382,
                  "height":281}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u21.jpg"}},
{
          "id":"aca6d171c3b14fdaace54120e1388482",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":465,
              "y":463.5},
            "size":{
              "width":145,
              "height":94}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96c3cb1f753d438f95aaca92a411717e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":465,
                  "y":463.5},
                "size":{
                  "width":145,
                  "height":94}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Selecionar Manifestação in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"selecionar_manifesta_ao.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u23.png"}},
{
          "id":"33b7dd60db884bb493eb626a5c239602",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":263,
              "y":558},
            "size":{
              "width":163,
              "height":93}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0ca992e46344500986014da571d3ed0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":263,
                  "y":558},
                "size":{
                  "width":163,
                  "height":93}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Acesso à Informação in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"acesso_a_informa_ao.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u25.png"}}]}},
  "masters":{
    "c3b312e0f4ed4c0bb3018e5ca722b50c":{
      "packageId":"c3b312e0f4ed4c0bb3018e5ca722b50c",
      "type":"Axure:Master",
      "name":"MasterOuvidoria",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"85041cc9a6574e6995adfae7d06a0ed6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":776,
                "height":768}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13c32486200e4ff188916d5c4c5dd53d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":776,
                    "height":768}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u1.jpg"}},
{
            "id":"6af9268f4a684618a3d22d2e33f87b18",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":540,
                "y":570},
              "size":{
                "width":200,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5a03389ad0f94aceb449f367debbd1d0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":540,
                    "y":570},
                  "size":{
                    "width":200,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u3.png"}},
{
            "id":"b105428545ea4d8caaf90e64e90e98ce",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":540,
                "y":190},
              "size":{
                "width":200,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"058af3d369864a16b0e46da395b65894",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":540,
                    "y":190},
                  "size":{
                    "width":200,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u3.png"}},
{
            "id":"acb38523bb214e7497cbd28b2ca26e91",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Rounded MT Bold', 'Arial Rounded MT'",
              "fontSize":"12px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0033CC,
                "opacity":1},
              "location":{
                "x":190,
                "y":164},
              "size":{
                "width":126,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aee5318bf07847c99662fb659f4942be",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Rounded MT Bold', 'Arial Rounded MT'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0033CC,
                    "opacity":1},
                  "location":{
                    "x":190,
                    "y":164},
                  "size":{
                    "width":126,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"660cfdf55c5b442f9574a2984b321745",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":180,
                "y":200},
              "size":{
                "width":200,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"99eb6015e68a4e9abf3a0e51107c7e86",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":180,
                    "y":200},
                  "size":{
                    "width":200,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u9.png"}},
{
            "id":"6dce9515c9164d5489b7b3e556cf9ed3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":180,
                "y":210},
              "size":{
                "width":200,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c1e04fb4630244a0bf26fdde812818d2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":180,
                    "y":210},
                  "size":{
                    "width":200,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u3.png"}},
{
            "id":"56003b8b0b10483085cb3bc23ef9b97d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negrito', 'Arial'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":24,
                "y":161},
              "size":{
                "width":70,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"78a482e4afeb4a3d9ffca2c3c2180110",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negrito', 'Arial'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":24,
                    "y":161},
                  "size":{
                    "width":70,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "1ce83de9629f429c8c3474f2e2e9de36":{
      "scriptId":"u0",
      "85041cc9a6574e6995adfae7d06a0ed6":{
        "scriptId":"u1"},
      "13c32486200e4ff188916d5c4c5dd53d":{
        "scriptId":"u2"},
      "6af9268f4a684618a3d22d2e33f87b18":{
        "scriptId":"u3"},
      "5a03389ad0f94aceb449f367debbd1d0":{
        "scriptId":"u4"},
      "b105428545ea4d8caaf90e64e90e98ce":{
        "scriptId":"u5"},
      "058af3d369864a16b0e46da395b65894":{
        "scriptId":"u6"},
      "acb38523bb214e7497cbd28b2ca26e91":{
        "scriptId":"u7"},
      "aee5318bf07847c99662fb659f4942be":{
        "scriptId":"u8"},
      "660cfdf55c5b442f9574a2984b321745":{
        "scriptId":"u9"},
      "99eb6015e68a4e9abf3a0e51107c7e86":{
        "scriptId":"u10"},
      "6dce9515c9164d5489b7b3e556cf9ed3":{
        "scriptId":"u11"},
      "c1e04fb4630244a0bf26fdde812818d2":{
        "scriptId":"u12"},
      "56003b8b0b10483085cb3bc23ef9b97d":{
        "scriptId":"u13"},
      "78a482e4afeb4a3d9ffca2c3c2180110":{
        "scriptId":"u14"}},
    "d3bc5ec3745944889c4e0ba806c23a8b":{
      "scriptId":"u15"},
    "a216607c7ced4c8ea7e177c36e6c631c":{
      "scriptId":"u16"},
    "c5ddcaf17b53428ea6ee0ac3908f4ec9":{
      "scriptId":"u17"},
    "45490e93d1cb49c999b667aefced80be":{
      "scriptId":"u18"},
    "703a8af572e94ce69b489fa526ae3a43":{
      "scriptId":"u19"},
    "ae15c0c4e38c4e47bf18c8940ba62bcd":{
      "scriptId":"u20"},
    "23d4793a18774883aaf183ddeeb8ae76":{
      "scriptId":"u21"},
    "8fcc53d3a6c04f9ab6faee5226508dab":{
      "scriptId":"u22"},
    "aca6d171c3b14fdaace54120e1388482":{
      "scriptId":"u23"},
    "96c3cb1f753d438f95aaca92a411717e":{
      "scriptId":"u24"},
    "33b7dd60db884bb493eb626a5c239602":{
      "scriptId":"u25"},
    "a0ca992e46344500986014da571d3ed0":{
      "scriptId":"u26"}}});