$axure.loadCurrentPage({
  "url":"login.html",
  "generationDate":new Date(1399640624725.66),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8033908c69b348588d679b04c60f3159",
    "type":"Axure:Page",
    "name":"Login",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8faabb18d3ef4560a9c5ba2d9847f3da",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"c3b312e0f4ed4c0bb3018e5ca722b50c"},
{
          "id":"412914260670490ca5e68f7cc320b295",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":204},
            "size":{
              "width":324,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2463e69158cc4374af2b50558b6457df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":204},
                "size":{
                  "width":324,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9732345cf9334e5e96922cfd54a529c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":580},
            "size":{
              "width":200,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69c2dbf4d4cf49258c4e06c577e06ad7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":580},
                "size":{
                  "width":200,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u3.png"}},
{
          "id":"70bd983fa0384c78a8943eb23b28b69a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":260},
            "size":{
              "width":96,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"117e483a10384fa08a5ea17600bb99d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":260},
                "size":{
                  "width":96,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1c2b799e15249d7adff0ca37383dc9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":311},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be9e4b6bd35b4afb8afc70c4220ea579",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":311},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"701f8ea2672247b69e61d87bbf99d66d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":276},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a9682fbf9b3947af8810bd061d4482cd",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":327},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0f19e3e03f5d45a2a5d0f9b975258eff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":429},
            "size":{
              "width":102,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c433ea66b4c0454cb54634682741bff0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":201,
                  "y":429},
                "size":{
                  "width":102,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Esqueci minha senha in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"esqueci_minha_senha.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37a34afe52744310bb51035c497c77a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":445},
            "size":{
              "width":120,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1a10fce634e4511a1db44abb251f4f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":445},
                "size":{
                  "width":120,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open CadastroManifestação in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"cadastromanifesta_ao.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"259bc0f9e81b40a3a6c848006acde470",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":190},
            "size":{
              "width":90,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87da584a86ac476ab9b9f3742d5e03d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":190},
                "size":{
                  "width":90,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u17.png"}},
{
          "id":"33a3505b5a5c40d9b92177598088c0cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negrito', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":24,
              "y":161},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ffd3521dab340a2a17d0c561e994cc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negrito', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":24,
                  "y":161},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc59b88a012345588f7b5507099e72aa",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":362},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Selecionar Manifestação in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"selecionar_manifesta_ao.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "c3b312e0f4ed4c0bb3018e5ca722b50c":{
      "packageId":"c3b312e0f4ed4c0bb3018e5ca722b50c",
      "type":"Axure:Master",
      "name":"MasterOuvidoria",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"85041cc9a6574e6995adfae7d06a0ed6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":776,
                "height":768}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"13c32486200e4ff188916d5c4c5dd53d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":776,
                    "height":768}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u1.jpg"}},
{
            "id":"6af9268f4a684618a3d22d2e33f87b18",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":540,
                "y":570},
              "size":{
                "width":200,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5a03389ad0f94aceb449f367debbd1d0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":540,
                    "y":570},
                  "size":{
                    "width":200,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u3.png"}},
{
            "id":"b105428545ea4d8caaf90e64e90e98ce",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":540,
                "y":190},
              "size":{
                "width":200,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"058af3d369864a16b0e46da395b65894",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":540,
                    "y":190},
                  "size":{
                    "width":200,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u3.png"}},
{
            "id":"acb38523bb214e7497cbd28b2ca26e91",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Rounded MT Bold', 'Arial Rounded MT'",
              "fontSize":"12px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0033CC,
                "opacity":1},
              "location":{
                "x":190,
                "y":164},
              "size":{
                "width":126,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aee5318bf07847c99662fb659f4942be",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Rounded MT Bold', 'Arial Rounded MT'",
                  "fontSize":"12px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0033CC,
                    "opacity":1},
                  "location":{
                    "x":190,
                    "y":164},
                  "size":{
                    "width":126,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"660cfdf55c5b442f9574a2984b321745",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":180,
                "y":200},
              "size":{
                "width":200,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"99eb6015e68a4e9abf3a0e51107c7e86",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":180,
                    "y":200},
                  "size":{
                    "width":200,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u9.png"}},
{
            "id":"6dce9515c9164d5489b7b3e556cf9ed3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":180,
                "y":210},
              "size":{
                "width":200,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c1e04fb4630244a0bf26fdde812818d2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":180,
                    "y":210},
                  "size":{
                    "width":200,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u3.png"}},
{
            "id":"56003b8b0b10483085cb3bc23ef9b97d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negrito', 'Arial'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":24,
                "y":161},
              "size":{
                "width":70,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"78a482e4afeb4a3d9ffca2c3c2180110",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negrito', 'Arial'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":24,
                    "y":161},
                  "size":{
                    "width":70,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "8faabb18d3ef4560a9c5ba2d9847f3da":{
      "scriptId":"u0",
      "85041cc9a6574e6995adfae7d06a0ed6":{
        "scriptId":"u1"},
      "13c32486200e4ff188916d5c4c5dd53d":{
        "scriptId":"u2"},
      "6af9268f4a684618a3d22d2e33f87b18":{
        "scriptId":"u3"},
      "5a03389ad0f94aceb449f367debbd1d0":{
        "scriptId":"u4"},
      "b105428545ea4d8caaf90e64e90e98ce":{
        "scriptId":"u5"},
      "058af3d369864a16b0e46da395b65894":{
        "scriptId":"u6"},
      "acb38523bb214e7497cbd28b2ca26e91":{
        "scriptId":"u7"},
      "aee5318bf07847c99662fb659f4942be":{
        "scriptId":"u8"},
      "660cfdf55c5b442f9574a2984b321745":{
        "scriptId":"u9"},
      "99eb6015e68a4e9abf3a0e51107c7e86":{
        "scriptId":"u10"},
      "6dce9515c9164d5489b7b3e556cf9ed3":{
        "scriptId":"u11"},
      "c1e04fb4630244a0bf26fdde812818d2":{
        "scriptId":"u12"},
      "56003b8b0b10483085cb3bc23ef9b97d":{
        "scriptId":"u13"},
      "78a482e4afeb4a3d9ffca2c3c2180110":{
        "scriptId":"u14"}},
    "412914260670490ca5e68f7cc320b295":{
      "scriptId":"u15"},
    "2463e69158cc4374af2b50558b6457df":{
      "scriptId":"u16"},
    "9732345cf9334e5e96922cfd54a529c5":{
      "scriptId":"u17"},
    "69c2dbf4d4cf49258c4e06c577e06ad7":{
      "scriptId":"u18"},
    "70bd983fa0384c78a8943eb23b28b69a":{
      "scriptId":"u19"},
    "117e483a10384fa08a5ea17600bb99d6":{
      "scriptId":"u20"},
    "e1c2b799e15249d7adff0ca37383dc9e":{
      "scriptId":"u21"},
    "be9e4b6bd35b4afb8afc70c4220ea579":{
      "scriptId":"u22"},
    "701f8ea2672247b69e61d87bbf99d66d":{
      "scriptId":"u23"},
    "a9682fbf9b3947af8810bd061d4482cd":{
      "scriptId":"u24"},
    "0f19e3e03f5d45a2a5d0f9b975258eff":{
      "scriptId":"u25"},
    "c433ea66b4c0454cb54634682741bff0":{
      "scriptId":"u26"},
    "37a34afe52744310bb51035c497c77a1":{
      "scriptId":"u27"},
    "f1a10fce634e4511a1db44abb251f4f9":{
      "scriptId":"u28"},
    "259bc0f9e81b40a3a6c848006acde470":{
      "scriptId":"u29"},
    "87da584a86ac476ab9b9f3742d5e03d2":{
      "scriptId":"u30"},
    "33a3505b5a5c40d9b92177598088c0cd":{
      "scriptId":"u31"},
    "8ffd3521dab340a2a17d0c561e994cc7":{
      "scriptId":"u32"},
    "fc59b88a012345588f7b5507099e72aa":{
      "scriptId":"u33"}}});