USE SIGEVEN
GO
	INSERT INTO SIGEVEN.SETOR(SG_COR, NM_COR)VALUES('AM', 'AMARELO');
	INSERT INTO SIGEVEN.SETOR(SG_COR, NM_COR)VALUES('AZ', 'AZUL');
	INSERT INTO SIGEVEN.SETOR(SG_COR, NM_COR)VALUES('BR','BRANCO');
	INSERT INTO SIGEVEN.SETOR(SG_COR, NM_COR)VALUES('CZ', 'CINZA');
	INSERT INTO SIGEVEN.SETOR(SG_COR, NM_COR)VALUES('LA', 'LARANJA');
	INSERT INTO SIGEVEN.SETOR(SG_COR, NM_COR)VALUES('LL', 'LILÁS');
	INSERT INTO SIGEVEN.SETOR(SG_COR, NM_COR)VALUES('MR', 'MARRON');
	INSERT INTO SIGEVEN.SETOR(SG_COR, NM_COR)VALUES('RS', 'ROSA');
	INSERT INTO SIGEVEN.SETOR(SG_COR, NM_COR)VALUES('SM', 'SALMÃO');
	INSERT INTO SIGEVEN.SETOR(SG_COR, NM_COR)VALUES('VC', 'VERDE CLARO');
	INSERT INTO SIGEVEN.SETOR(SG_COR, NM_COR)VALUES('VD', 'VERDE');
	INSERT INTO SIGEVEN.SETOR(SG_COR, NM_COR)VALUES('VM', 'VERMELHO');
	INSERT INTO SIGEVEN.SETOR(SG_COR, NM_COR)VALUES('AE', 'AZUL ESCURO');
	INSERT INTO SIGEVEN.SETOR(SG_COR, NM_COR)VALUES('RX', 'ROXO');
GO